/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-bright": "#f6fafe",
        "secondary-fixed-dim": "#b9c7df",
        "primary-container": "#2e5bff",
        "on-tertiary-fixed-variant": "#005049",
        "secondary-fixed": "#d5e3fc",
        "on-secondary-fixed": "#0d1c2e",
        "surface-container-lowest": "#ffffff",
        "error": "#ba1a1a",
        "on-secondary-container": "#57657a",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#dde1ff",
        "on-error-container": "#93000a",
        "tertiary": "#006058",
        "secondary": "#515f74",
        "on-surface-variant": "#434656",
        "surface-container-highest": "#dfe3e7",
        "surface-dim": "#d6dade",
        "on-background": "#171c1f",
        "surface-tint": "#124af0",
        "tertiary-fixed": "#89f5e7",
        "tertiary-fixed-dim": "#6bd8cb",
        "on-error": "#ffffff",
        "on-tertiary-container": "#b2fff3",
        "on-primary-fixed-variant": "#0035be",
        "on-surface": "#171c1f",
        "primary": "#0040e0",
        "surface-container-low": "#f0f4f8",
        "inverse-on-surface": "#edf1f5",
        "on-primary-fixed": "#001356",
        "on-secondary": "#ffffff",
        "outline": "#747688",
        "primary-fixed-dim": "#b8c3ff",
        "inverse-primary": "#b8c3ff",
        "outline-variant": "#c4c5d9",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#00201d",
        "inverse-surface": "#2c3134",
        "background": "#f6fafe",
        "secondary-container": "#d5e3fc",
        "error-container": "#ffdad6",
        "surface-container": "#eaeef2",
        "surface": "#f6fafe",
        "surface-container-high": "#e4e9ed",
        "surface-variant": "#dfe3e7",
        "tertiary-container": "#007b71",
        "on-primary-container": "#efefff",
        "on-secondary-fixed-variant": "#3a485b"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
