"""Added indexes for faster loads

Revision ID: 6e027db95e13
Revises: a903c9522308
Create Date: 2026-03-07 14:19:51.891671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e027db95e13'
down_revision: Union[str, Sequence[str], None] = 'a903c9522308'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email_jobs', 'status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('CREATED', 'PROCESSING', 'SCHEDULED', 'RUNNING', 'COMPLETED', 'FAILED', name='emailjobstatus'),
               existing_nullable=False)
    op.execute("ALTER TYPE emailjobstatus ADD VALUE 'PROCESSING'")
    op.create_index('ix_job_sentat', 'email_tasks', ['job_id', 'sent_at'], unique=False)
    op.create_index('ix_job_status', 'email_tasks', ['job_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_job_status', table_name='email_tasks')
    op.drop_index('ix_job_sentat', table_name='email_tasks')
    op.alter_column('email_jobs', 'status',
               existing_type=sa.Enum('CREATED', 'PROCESSING', 'SCHEDULED', 'RUNNING', 'COMPLETED', 'FAILED', name='emailjobstatus'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
    # ### end Alembic commands ###
