"""Added indexing

Revision ID: 7cbfc363e396
Revises: 87f14b468b03
Create Date: 2026-03-25 11:47:45.685970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cbfc363e396'
down_revision: Union[str, Sequence[str], None] = '87f14b468b03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_task_outbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['email_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_task_outbox_is_processed'), 'email_task_outbox', ['is_processed'], unique=False)
    op.create_unique_constraint('uq_job_analytics_row', 'email_job_analytics', ['job_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_job_analytics_row', 'email_job_analytics', type_='unique')
    op.drop_index(op.f('ix_email_task_outbox_is_processed'), table_name='email_task_outbox')
    op.drop_table('email_task_outbox')
    # ### end Alembic commands ###
