"""Added indexes

Revision ID: 87f14b468b03
Revises: dd0bb0ac6154
Create Date: 2026-03-24 14:35:56.613096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87f14b468b03'
down_revision: Union[str, Sequence[str], None] = 'dd0bb0ac6154'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_email_jobs_created_at'), 'email_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_email_jobs_scheduled_at'), 'email_jobs', ['scheduled_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_jobs_scheduled_at'), table_name='email_jobs')
    op.drop_index(op.f('ix_email_jobs_created_at'), table_name='email_jobs')
    # ### end Alembic commands ###
