"""Added client id

Revision ID: a903c9522308
Revises: ef2af4a94ffa
Create Date: 2026-02-27 15:53:05.769400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a903c9522308'
down_revision: Union[str, Sequence[str], None] = 'ef2af4a94ffa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_accounts', sa.Column('oauth_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_accounts', 'oauth_id')
    # ### end Alembic commands ###
