"""Using new auth tables

Revision ID: d2097f655549
Revises: 
Create Date: 2026-02-18 23:21:55.268635

"""
from typing import Sequence, Union
import fastapi_users_db_sqlalchemy
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2097f655549'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Enum('GSHEET', 'CSV', name='source_type_enum'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('json_schema', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('email_column', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasets_user_id'), 'datasets', ['user_id'], unique=False)
    op.create_table('email_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('SENDGRID', 'GMAIL', name='email_provider_enum'), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('email_address', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_accounts_user_id'), 'email_accounts', ['user_id'], unique=False)
    op.create_table('dataset_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('row_data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_rows_dataset_id'), 'dataset_rows', ['dataset_id'], unique=False)
    op.create_table('email_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('email_account_id', sa.Integer(), nullable=False),
    sa.Column('prompt_template', sa.String(), nullable=True),
    sa.Column('subject_template', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'SCHEDULED', 'RUNNING', 'COMPLETED', 'FAILED', name='emailjobstatus'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('throttle_per_minute', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['email_account_id'], ['email_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_jobs_user_id'), 'email_jobs', ['user_id'], unique=False)
    op.create_table('email_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('dataset_row_id', sa.Integer(), nullable=False),
    sa.Column('recipient_email', sa.String(), nullable=False),
    sa.Column('rendered_subject', sa.String(), nullable=True),
    sa.Column('rendered_body', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'SENT', 'FAILED', 'BOUNCED', 'DELIVERED', 'OPENED', 'DEFERRED', name='emailtaskstatus'), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_row_id'], ['dataset_rows.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['email_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'dataset_row_id', name='uq_job_row')
    )
    op.create_index(op.f('ix_email_tasks_job_id'), 'email_tasks', ['job_id'], unique=False)
    op.create_table('email_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_task_id', sa.Integer(), nullable=False),
    sa.Column('email_job_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['email_job_id'], ['email_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['email_task_id'], ['email_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_events_email_job_id'), 'email_events', ['email_job_id'], unique=False)
    op.create_index(op.f('ix_email_events_email_task_id'), 'email_events', ['email_task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_events_email_task_id'), table_name='email_events')
    op.drop_index(op.f('ix_email_events_email_job_id'), table_name='email_events')
    op.drop_table('email_events')
    op.drop_index(op.f('ix_email_tasks_job_id'), table_name='email_tasks')
    op.drop_table('email_tasks')
    op.drop_index(op.f('ix_email_jobs_user_id'), table_name='email_jobs')
    op.drop_table('email_jobs')
    op.drop_index(op.f('ix_dataset_rows_dataset_id'), table_name='dataset_rows')
    op.drop_table('dataset_rows')
    op.drop_index(op.f('ix_email_accounts_user_id'), table_name='email_accounts')
    op.drop_table('email_accounts')
    op.drop_index(op.f('ix_datasets_user_id'), table_name='datasets')
    op.drop_table('datasets')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
