"""Provide ID upgrade

Revision ID: dd0bb0ac6154
Revises: e3117f03c3e3
Create Date: 2026-03-10 00:46:00.111453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd0bb0ac6154'
down_revision: Union[str, Sequence[str], None] = 'e3117f03c3e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'email_events', ['provider_event_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'email_events', type_='unique')
    # ### end Alembic commands ###
