"""Provider ID for emai_event

Revision ID: e3117f03c3e3
Revises: 2f29bcfba95b
Create Date: 2026-03-10 00:40:41.995934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3117f03c3e3'
down_revision: Union[str, Sequence[str], None] = '2f29bcfba95b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_events', sa.Column('provider_event_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_events', 'provider_event_id')
    # ### end Alembic commands ###
