"""Added encryption to data

Revision ID: ef2af4a94ffa
Revises: e173f088546e
Create Date: 2026-02-27 11:13:17.375242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'ef2af4a94ffa'
down_revision: Union[str, Sequence[str], None] = 'e173f088546e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_accounts', sa.Column('_config', sa.LargeBinary(), nullable=False))
    op.drop_column('email_accounts', 'config')
    op.drop_column('email_accounts', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_accounts', sa.Column('name', sa.VARCHAR(), nullable=False))
    op.add_column('email_accounts', sa.Column('config', sqlite.JSON(), nullable=False))
    op.drop_column('email_accounts', '_config')
    # ### end Alembic commands ###
